version: "3"

services:
  web:
    build: ./docker/web/
    # restart: always
    network_mode: bridge # 00-nginx-proxy が VIRTUAL_HOST 振り分けできるようにネットワーク共有
    links:
      - mailhog # mailhogコンテナとリンク
      - postfix # postfix コンテナとリンク
    volumes:
      # ~www-data: host://./www/ => docker://web:/var/www/
      ## DocumentRoot: host://./www/app/public/ => docker://web:/var/app/public/
      - ./www/:/var/www/
      # 設定ファイル
      - ./docker/web/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/web/conf/php.ini:/etc/php.d/php.ini
    environment:
      # user ID: www-data のユーザIDを docker 実行ユーザIDに合わせたい場合に利用
      ## ユーザIDを合わせないと ./www/ (docker://web:/var/www/) 内のファイル編集が出来なくなる
      UID: ${UID}
      # Composer設定
      COMPOSER_ALLOW_SUPERUSER: 1 # root権限での実行を許可
      COMPOSER_NO_INTERACTION: 1  # 非対話的にインストール
      # TimeZone設定
      TZ: Asia/Tokyo
      # VirtualHost (nginx-proxy)
      VIRTUAL_HOST: slim-mailform.localhost
      # LETSENCRYPT_HOST: slim-mailform.localhost
      # LETSENCRYPT_EMAIL: admin@slim-mailform.localhost
      CERT_NAME: default # ローカル開発時は自己証明書利用
      VIRTUAL_PORT: 80
  
  # local SMTP server + Mail catcher
  mailhog:
    image: mailhog/mailhog
    network_mode: bridge # 00-nginx-proxy が VIRTUAL_HOST 振り分けできるようにネットワーク共有
    # ports:
    #   - 17401:8025 # HTTP Port
    #   - 17425:1025 # SMTP Port
    environment:
      # VirtualHost (nginx-proxy)
      VIRTUAL_HOST: mail.slim-mailform.localhost
      # LETSENCRYPT_HOST: mail.slim-mailform.localhost
      # LETSENCRYPT_EMAIL: admin@slim-mailform.localhost
      CERT_NAME: default # ローカル開発時は自己証明書利用
      VIRTUAL_PORT: 8025
  
  # postfix smtp server
  postfix:
      build:
        context: ./docker/postfix
        args:
          # リレー先 smtp 設定
          RELAY_SMTP_HOST: $RELAY_SMTP_HOST
          RELAY_SMTP_PORT: $RELAY_SMTP_PORT
          RELAY_SMTP_USER: $RELAY_SMTP_USER
          RELAY_SMTP_PASSWORD: $RELAY_SMTP_PASSWORD
      network_mode: bridge
      tty: true
      environment:
        # TimeZone設定
        TZ: Asia/Tokyo
