version: "3"

services:
  web:
    build: ./docker/web/
    # restart: always
    network_mode: bridge # 00-nginx-proxy が VIRTUAL_HOST 振り分けできるようにネットワーク共有
    links:
      - postfix # postfix コンテナとリンク
    volumes:
      - ./app/:/var/www/app/
      # 設定ファイル
      - ./docker/web/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/web/conf/php.ini:/etc/php.d/php.ini
    # DocumentRoot のパーミッション問題修正のため docker 実行ユーザ UID を apache ユーザ（www-data）UID を合わせて apache 起動
    command: bash -c 'usermod -o -u ${UID} www-data; groupmod -o -g ${UID} www-data; apachectl -D FOREGROUND'
    environment:
      # Composer設定
      COMPOSER_ALLOW_SUPERUSER: 1 # root権限での実行を許可
      COMPOSER_NO_INTERACTION: 1  # 非対話的にインストール
      # TimeZone設定
      TZ: Asia/Tokyo
      # VirtualHost (nginx-proxy)
      VIRTUAL_HOST: slim-mailform.localhost
      # LETSENCRYPT_HOST: slim-mailform.localhost
      # LETSENCRYPT_EMAIL: admin@slim-mailform.localhost
      CERT_NAME: default # ローカル開発時は自己証明書利用
      VIRTUAL_PORT: 80
  
  # postfix smtp server
  postfix:
      build:
        context: ./docker/postfix
        args:
          # リレー先 smtp 設定
          RELAY_SMTP_HOST: $RELAY_SMTP_HOST
          RELAY_SMTP_PORT: $RELAY_SMTP_PORT
          RELAY_SMTP_USER: $RELAY_SMTP_USER
          RELAY_SMTP_PASSWORD: $RELAY_SMTP_PASSWORD
      network_mode: bridge
      tty: true
      environment:
        # local smtp server 設定
        
        # TimeZone設定
        TZ: Asia/Tokyo
